version: '3.8'

services:
  mymaid-app:
    build: .
    ports:
      - "3000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
      # Add your environment variables here for testing
      # - FIREBASE_PROJECT_ID=your-project-id
      # - REACT_APP_FIREBASE_API_KEY=your-api-key
      # etc...
    volumes:
      # Optional: Mount env file for local testing
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: mymaid-network
